
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';

export const RECEIVE_DESIGNS = 'RECEIVE_DESIGNS';
export const RECEIVE_DESIGN = 'RECEIVE_DESIGN';

export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';

export const SET_CURRENT_DESIGN = 'SET_CURRENT_DESIGN';
