
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';

export const RECEIVE_DESIGNS = 'RECEIVE_DESIGNS';
export const RECEIVE_DESIGN = 'RECEIVE_DESIGN';

export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';

export const SET_CURRENT_DESIGN = 'SET_CURRENT_DESIGN';

export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const DESTROY_CART = 'DESTROY_CART';
export const GET_CART_CONTENT = 'GET_CART_CONTENT';

export const SET_USER = 'SET_USER';
